name: Uploading files

on:
  push:
    branches:
      - master

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Replace database config values
        run: |
          sed -i "s/your_database_host/${{ secrets.SQL_HOST }}/g" inc/config.php
          sed -i "s/your_database_username/${{ secrets.SQL_USER }}/g" inc/config.php
          sed -i "s/your_database_password/${{ secrets.SQL_PASS }}/g" inc/config.php
          sed -i "s/your_database_name/${{ secrets.SQL_DATABASE }}/g" inc/config.php

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          protocol: ftp
          local-dir: ./
          server-dir: ./
